# Generated by Django 5.0.2 on 2024-02-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0002_pedidocompra_cantidad_pedidocompra_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidocompra',
            name='tipo',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=6, null=True),
        ),
    ]
