# Generated by Django 5.0.2 on 2024-02-21 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0005_rename_detallepedidocompra_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DetallePedido',
            new_name='DetallePedidoCompra',
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=6, null=True)),
                ('fecha_pedido', models.DateField()),
                ('descripcion', models.TextField(null=True)),
                ('cantidad', models.PositiveIntegerField(null=True)),
                ('productos', models.ManyToManyField(through='inventario_app.DetallePedidoCompra', to='inventario_app.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_app.proveedor')),
            ],
        ),
        migrations.AlterField(
            model_name='detallepedidocompra',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_app.pedidocompra'),
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
    ]
