# Generated by Django 5.0.2 on 2024-02-22 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0007_rename_detallepedidocompra_detallepedido_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_app.proveedor'),
        ),
    ]
