# Generated by Django 5.0.2 on 2024-02-23 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0008_alter_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
