# Generated by Django 5.0.2 on 2024-02-24 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_app', '0009_alter_pedido_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='productos',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario_app.producto'),
        ),
    ]
